activation: relu
custom_decoder: null
custom_encoder: null
d_model: 64
dim_feedforward: 512
dropout: 0.1
input_chunk_length: 30
input_size: 37
likelihood: null
lr_scheduler_cls: null
lr_scheduler_kwargs: null
nhead: 4
norm_type: null
nr_params: 1
num_decoder_layers: 3
num_encoder_layers: 3
optimizer_cls: !!python/name:torch.optim.adamw.AdamW ''
optimizer_kwargs:
  lr: 0.0003
output_chunk_length: 7
output_chunk_shift: 0
output_size: 1
train_sample_shape:
- !!python/tuple
  - 30
  - 1
- !!python/tuple
  - 30
  - 36
- null
- !!python/tuple
  - 7
  - 1
use_reversible_instance_norm: false
