services:
  backend:
    build: .
    command: poetry run uvicorn tasks_support_system_ai.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s


  frontend:
    build: .
    command: poetry run streamlit run tasks_support_system_ai/web/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      IS_DOCKER: 1
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    networks:
      - minio_network
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_SERVER_URL: "https://data.pyrogn.ru"
      MINIO_BROWSER_REDIRECT_URL: "https://data.pyrogn.ru/ui/"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - minio
    networks:
      - minio_network

volumes:
  minio_data:

networks:
  app-network:
    driver: bridge
  minio_network:
    driver: bridge
