services:
  backend:
    build: .
    command: poetry run uvicorn tasks_support_system_ai.main:app --host 0.0.0.0 --port 8000
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=INFO
    env_file:
      - ./.env
    networks:
      - app-network
    profiles:
      - app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 2s

  frontend:
    build: .
    command: poetry run streamlit run tasks_support_system_ai/web/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=INFO
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    profiles:
      - app
    depends_on:
      backend:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    networks:
      - nginx_network
    volumes:
      - minio_data:/data
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_BROWSER_REDIRECT_URL: "https://minio.pyrogn.ru"
      MINIO_SERVER_URL: "https://s3.pyrogn.ru"
      MINIO_LOGGER: "console"
      MINIO_HTTP_TRACE: "/dev/stdout"
      MINIO_API_LOG_LEVEL: "debug"
    command: server /data --console-address ":9001"
    profiles:
      - production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/minio.conf:/etc/nginx/conf.d/minio.conf:ro
    profiles:
      - production
    networks:
      - nginx_network
      - app-network

volumes:
  minio_data:
    driver: local
  logs:

networks:
  app-network:
    driver: bridge
  nginx_network:
    driver: bridge
