decoder_output_dim: 16
dropout: 0.1
future_cov_dim: 3
hidden_size: 128
input_chunk_length: 30
input_dim: 40
likelihood: null
lr_scheduler_cls: null
lr_scheduler_kwargs: null
nr_params: 1
num_decoder_layers: 1
num_encoder_layers: 1
optimizer_cls: !!python/name:torch.optim.adamw.AdamW ''
optimizer_kwargs:
  lr: 0.0003
output_chunk_length: 7
output_chunk_shift: 0
output_dim: 1
static_cov_dim: 0
temporal_decoder_hidden: 32
temporal_hidden_size_future: 128
temporal_hidden_size_past: 128
temporal_width_future: 4
temporal_width_past: 4
train_sample_shape:
- !!python/tuple
  - 30
  - 1
- !!python/tuple
  - 30
  - 36
- !!python/tuple
  - 30
  - 3
- !!python/tuple
  - 7
  - 3
- null
- !!python/tuple
  - 7
  - 1
use_layer_norm: false
use_reversible_instance_norm: false
