name: Test Deploy

on:
  push:
    branches: [ main , test-deploy*]
  workflow_dispatch:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Connect to Headscale
        run: |
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
          sudo apt-get update
          sudo apt-get install -y tailscale
          sudo systemctl start tailscaled

          sudo tailscale up \
            --login-server=${{ secrets.TAILSCALE_SERVER }} \
            --authkey=${{ secrets.TAILSCALE_AUTHKEY }} \
            --accept-routes \
            --accept-dns=false

          sleep 5
          tailscale status

      - name: Generate SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Test connection and sync
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "echo 'Connection successful'"

          rsync -av --exclude='.git' \
                    --exclude='.github' \
                    --exclude='notebooks' \
                    ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/opt/test-deploy/

          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "ls -la /opt/test-deploy"
